name: flutter_course
packages:
  - core/**
  - features/**

commands:
  bootstrap:
    environment:
      sdk: ^3.8.0

    dependencies:
      dio: ^5.8.0+1
      get_it: ^8.0.3
      injectable: ^2.5.0
      injectable_generator: ^2.7.0
      json_annotation: ^4.9.0

    dev_dependencies:
      flutter_lints: ^5.0.0
      json_serializable: ^6.9.5
      build_runner: ^2.5.4

scripts:
  bootstrap: melos bootstrap
  clean: melos clean
  cleanAndBootstrap: melos clean && melos bootstrap
  format: melos format
  test:
    run: melos exec --concurrency=1 -- flutter test
